version: "3.9"

services:
  api:
    build: ./backend
    container_name: fica_api
    restart: always
    ports:
      - "3025:8080" # API accesible en localhost:3025
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: bitnami/postgresql:17.4.0
    platform: linux/amd64
    ports:
      - ${POSTGRESQL_PORT}:5432
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
    env_file:
      - backend/.env
    networks:
      - docker-fastapi-base

  pgadmin:
    image: dpage/pgadmin4
    container_name: fica_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    env_file:
      - backend/.env
    ports:
      - "5050:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fica_frontend
    restart: always
    ports:
      - "3000:5173" # Acceso a la app React/Vite en localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./.data/redis:/data

volumes:
  db_data:
